Repository AY2425S1-CS2103T-W12-3/tp, pull requests merged in 2024-11, with the labels that each got.

#115 Improve Find Telegram Handle Coverage
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/SwitchThemeCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Medium, severity.Medium

#118 Validation regex
  src/main/java/seedu/address/model/person/ContactType.java
  src/main/java/seedu/address/model/person/ModuleName.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ModuleNameTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#113 Update edit command to work for ContactType
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, severity.Medium

#122 Edit ug
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#127 Update optionality of TelegramHandle field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TelegramHandleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#128 Update find telegram handle to be case-insensitive
  src/main/java/seedu/address/model/person/TelegramHandleContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/TelegramHandleContainsKeywordsPredicateTest.java
Labels: type.Bug, priority.Medium

#119 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavid.png
  docs/images/help.png
  docs/images/helpMessage.png
Labels: priority.High

#130 Update help window to open URL
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium

#135 Update Contact Type to include School
  src/main/java/seedu/address/logic/commands/FilterContactTypeCommand.java
  src/main/java/seedu/address/model/person/ContactType.java
  src/main/java/seedu/address/model/person/ContactTypeEnum.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, severity.Medium

#132 Add import feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/CsvToJsonConverter.java
  src/main/java/seedu/address/storage/JsonImporter.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/exceptions/ConverterException.java
  src/main/java/seedu/address/storage/exceptions/ImporterException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#145 Make ModuleName and Remark fields optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#146 Improve find TelegramHandle command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#142 Update UG
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#140 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.Low, severity.Low

#152 Email validation
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: priority.Medium

#154 Handle invalid inputs for find command
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Medium, severity.Medium

#156 Fix Switch Command Bug
  src/main/java/seedu/address/storage/ThemePreference.java
Labels: priority.High, alpha-bug

#158 Update Help in UG
  docs/UserGuide.md
  docs/images/HelpWindow.png
Labels: priority.Medium, severity.Medium

#150 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#161 Improve Error Message for Unknown Commands
  src/main/java/seedu/address/logic/Messages.java
Labels: severity.Low, alpha-bug

#170 Improve ModuleName constraints message
  src/main/java/seedu/address/model/person/ModuleName.java
Labels: priority.Medium

#172 Fix broken links in navigation table
  docs/UserGuide.md
Labels: priority.High

#164 Update Switch Command Success Message
  src/main/java/seedu/address/logic/commands/SwitchThemeCommand.java
Labels: severity.Low, alpha-bug

#173 Fix command line tutorial link in UG
  docs/UserGuide.md
Labels: priority.Medium

#175 Improve constraints message for Tag
  src/main/java/seedu/address/model/tag/Tag.java
Labels: severity.Low

#177 Change Find Telegram Handle Implementation
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindTelegramHandleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTelegramHandleCommandParser.java
  src/main/java/seedu/address/model/person/TelegramHandleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTelegramHandleCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTelegramHandleCommandParserTest.java
Labels: priority.High, severity.High, alpha-bug

#178 Developer guide update
  docs/DeveloperGuide.md
Labels: priority.Medium

#180 Update user guide
  docs/UserGuide.md
  docs/images/findtagNeighbourFamily.png
  docs/images/findteleAlexDavid.png
  docs/images/switchDark.png
Labels: priority.High

#185 Fix import feature bugs
  importTestCases/2101TAs - Base sheet.csv
  importTestCases/2101TAs - Different order.csv
  importTestCases/2101TAs - Duplicate entries.csv
  importTestCases/2101TAs - Invalid inputs.csv
  importTestCases/2101TAs - Missing fields.csv
  importTestCases/2101TAs - Unnecessary column.csv
  importTestCases/README.txt
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/ContactType.java
  src/main/java/seedu/address/storage/CsvToJsonConverter.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonImporter.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, severity.High

#182 Fix duplicate fields bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#188 Update UG with import feature information
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/storage/CsvToJsonConverter.java
Labels: priority.High

#189 Fix spelling error
  docs/DeveloperGuide.md
Labels: severity.Low, alpha-bug

#194 Edit import command to support optional modname
  docs/UserGuide.md
  importTestCases/README.txt
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: severity.High, alpha-bug

#192 Edit ug
  docs/UserGuide.md
  docs/images/ImportCommand.png
  docs/images/csvInImport.png
Labels: severity.Low, alpha-bug

#255 Fix bugs in UG
  docs/UserGuide.md
Labels: severity.Low

#261 Fix bugs in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SwitchThemeSequenceDiagram.puml
Labels: priority.Medium, severity.Medium

#258 Fix Remark Error Message Typo
  src/main/java/seedu/address/model/person/Remark.java
Labels: type.Bug

#262 Fix bugs in UG and error message of filter command
  docs/UserGuide.md
  docs/images/switchLight.png
  src/main/java/seedu/address/logic/parser/FilterContactTypeCommandParser.java
Labels: type.Bug, priority.High

#263 Update Known Issues
  docs/UserGuide.md
Labels: type.Bug

#260 Replace AB3 keywords with UniLink
  docs/index.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/unilink_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug

#267 Update UG with information on import command
  docs/UserGuide.md
Labels: type.Enhancement

#268 Fix navigation table bug and enlarge DG photos size
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High

#273 Remove traces of AB3
  docs/site.json
Labels: type.Bug, priority.High

#271 Update landing page badges and website name
  docs/images/UniLink-Logo.png
  docs/index.md
  docs/site.json
Labels: type.Enhancement

#275 Add examples to planned enhancements in DG
  docs/DeveloperGuide.md
  docs/images/emptySpaceUiBug.png
Labels: type.Enhancement

#278 Improve code coverage
  src/test/java/seedu/address/storage/ThemePreferenceTest.java
Labels: priority.Medium, severity.Medium

#282 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#283 Remove extra space
  docs/UserGuide.md
Labels: priority.High
